# Generated by Django 2.1.4 on 2018-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181212_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='descrption_text',
            new_name='descrptiontext',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='descrption_title',
            new_name='descrptiontitle',
        ),
    ]
