# Generated by Django 2.1.4 on 2018-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181212_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='descrptiontext',
            new_name='descriptiontext',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='descrptiontitle',
            new_name='descriptiontitle',
        ),
    ]
