# Generated by Django 2.1.4 on 2018-12-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181212_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footerpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footertitle', models.CharField(max_length=200)),
                ('footertext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gyanpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyantitle', models.CharField(max_length=200)),
                ('gyantext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heropage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herotitle', models.CharField(max_length=200)),
                ('herotext', models.TextField()),
                ('button', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processtext', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
