# Generated by Django 2.1.4 on 2018-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181213_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyanpage',
            name='button',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heropage',
            name='button',
            field=models.URLField(blank=True, null=True),
        ),
    ]
