# Generated by Django 2.1.4 on 2018-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181213_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
