# Generated by Django 2.1.4 on 2018-12-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_process_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gyanpage',
            name='button',
        ),
        migrations.RemoveField(
            model_name='heropage',
            name='button',
        ),
    ]
