# Generated by Django 2.1.4 on 2018-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181227_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
